Repository palayo-auction/palayo-auction, pull requests merged in 2025-04, with the labels that each got.

#18 feat: Auction CRUD 및 스케줄러 구현
  .gitignore
  src/main/java/com/example/palayo/PalayoApplication.java
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/palayo/common/response/PageResponse.java
  src/main/java/com/example/palayo/common/response/Response.java
  src/main/java/com/example/palayo/common/util/.gitkeep
  src/main/java/com/example/palayo/domain/auction/controller/.gitkeep
  src/main/java/com/example/palayo/domain/auction/controller/AuctionController.java
  src/main/java/com/example/palayo/domain/auction/dto/.gitkeep
  src/main/java/com/example/palayo/domain/auction/dto/request/CreateAuctionRequest.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionListResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/MyAuctionDetailResponse.java
  src/main/java/com/example/palayo/domain/auction/entity/Auction.java
  src/main/java/com/example/palayo/domain/auction/enums/AuctionStatus.java
  src/main/java/com/example/palayo/domain/auction/repository/.gitkeep
  src/main/java/com/example/palayo/domain/auction/repository/AuctionRepository.java
  src/main/java/com/example/palayo/domain/auction/scheduler/AuctionScheduler.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionServiceHelper.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionTimeUtils.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionValidator.java
  src/main/java/com/example/palayo/domain/auction/util/TimeFormatter.java
  src/main/java/com/example/palayo/domain/auctionhistory/controller/.gitkeep
  src/main/java/com/example/palayo/domain/auctionhistory/controller/AuctionHistoryController.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/.gitkeep
  src/main/java/com/example/palayo/domain/auctionhistory/dto/CreateBidRequest.java
  src/main/java/com/example/palayo/domain/auctionhistory/entity/AuctionHistory.java
  src/main/java/com/example/palayo/domain/auctionhistory/repository/.gitkeep
  src/main/java/com/example/palayo/domain/auctionhistory/repository/AuctionHistoryRepository.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/.gitkeep
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/BidService.java
  src/main/java/com/example/palayo/domain/user/controller/UserController.java
  src/main/java/com/example/palayo/domain/user/service/UserService.java
  src/main/resources/prod/application-datasource.yml
  src/main/resources/prod/application-jwt.yml
  src/main/resources/prod/application-prod.yml
Labels: feat

#20 Fix/item
  src/main/java/com/example/palayo/domain/item/controller/ItemController.java
  src/main/java/com/example/palayo/domain/item/repository/ItemRepository.java
  src/main/java/com/example/palayo/domain/item/repository/ItemRepositoryImpl.java
  src/main/java/com/example/palayo/domain/user/controller/UserController.java
  src/main/java/com/example/palayo/domain/user/service/UserService.java
Labels: fix

#14 Feat/dib CRUD 구현 완료 (추후 Auction merge 됐을 때 수정 가능성 있음)
  .gitignore
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/domain/dib/controller/.gitkeep
  src/main/java/com/example/palayo/domain/dib/controller/DibController.java
  src/main/java/com/example/palayo/domain/dib/dto/.gitkeep
  src/main/java/com/example/palayo/domain/dib/dto/response/DibListResponse.java
  src/main/java/com/example/palayo/domain/dib/dto/response/DibResponse.java
  src/main/java/com/example/palayo/domain/dib/entity/.gitkeep
  src/main/java/com/example/palayo/domain/dib/entity/Dib.java
  src/main/java/com/example/palayo/domain/dib/repository/.gitkeep
  src/main/java/com/example/palayo/domain/dib/repository/DibRepository.java
  src/main/java/com/example/palayo/domain/dib/service/.gitkeep
  src/main/java/com/example/palayo/domain/dib/service/DibService.java
  src/test/java/com/example/palayo/domain/dib/service/DibServiceTest.java
Labels: feat

#25 Feat/auction: AuctionHistory CRUD 구현
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/domain/auction/controller/AuctionController.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionListResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/MyAuctionDetailResponse.java
  src/main/java/com/example/palayo/domain/auction/entity/Auction.java
  src/main/java/com/example/palayo/domain/auction/repository/AuctionRepository.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionServiceHelper.java
  src/main/java/com/example/palayo/domain/auctionhistory/controller/AuctionHistoryController.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/CreateBidRequest.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/request/CreateBidRequest.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/response/BidHistoryResponse.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/response/BidResponse.java
  src/main/java/com/example/palayo/domain/auctionhistory/entity/AuctionHistory.java
  src/main/java/com/example/palayo/domain/auctionhistory/repository/AuctionHistoryRepository.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryServiceHelper.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/BidService.java
  src/main/java/com/example/palayo/domain/deposithistory/controller/.gitkeep
  src/main/java/com/example/palayo/domain/deposithistory/dto/.gitkeep
  src/main/java/com/example/palayo/domain/deposithistory/entity/.gitkeep
  src/main/java/com/example/palayo/domain/deposithistory/repository/.gitkeep
  src/main/java/com/example/palayo/domain/deposithistory/service/.gitkeep
Labels: feat

#27 Feat/payment 토스페이먼츠 이용한 결제 구현, 포인트 충전, 포인트 증감 로그 완성
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/palayo/config/RestTemplateConfig.java
  src/main/java/com/example/palayo/config/SecurityConfig.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryServiceHelper.java
  src/main/java/com/example/palayo/domain/deposithistory/controller/DepositHistoryController.java
  src/main/java/com/example/palayo/domain/deposithistory/dto/DepositHistoryResponse.java
  src/main/java/com/example/palayo/domain/payment/TossPaymentClient.java
  src/main/java/com/example/palayo/domain/payment/controller/PaymentController.java
  src/main/java/com/example/palayo/domain/payment/dto/request/PaymentConfirmRequest.java
  src/main/java/com/example/palayo/domain/payment/dto/response/PaymentConfirmResponse.java
  src/main/java/com/example/palayo/domain/payment/entity/Payment.java
  src/main/java/com/example/palayo/domain/payment/repostiory/PaymentRepository.java
  src/main/java/com/example/palayo/domain/payment/service/PaymentService.java
  src/main/java/com/example/palayo/domain/pointhistory/controller/.gitkeep
  src/main/java/com/example/palayo/domain/pointhistory/controller/PointHistoriesController.java
  src/main/java/com/example/palayo/domain/pointhistory/dto/.gitkeep
  src/main/java/com/example/palayo/domain/pointhistory/dto/PointHistoriesResponse.java
  src/main/java/com/example/palayo/domain/pointhistory/entity/.gitkeep
  src/main/java/com/example/palayo/domain/pointhistory/entity/PointHistories.java
  src/main/java/com/example/palayo/domain/pointhistory/repository/.gitkeep
  src/main/java/com/example/palayo/domain/pointhistory/repository/PointHistoriesRepository.java
  src/main/java/com/example/palayo/domain/pointhistory/service/.gitkeep
  src/main/java/com/example/palayo/domain/pointhistory/service/PointHistoriesService.java
  src/main/java/com/example/palayo/domain/user/entity/User.java
  src/main/java/com/example/palayo/domain/user/enums/PointType.java
Labels: feat

#29 style : 클래스명 수정, 부정확한 메서드명 수정, auth 패키지 도메인 패키지 안으로 이동
  src/main/java/com/example/palayo/domain/auth/controller/AuthController.java
  src/main/java/com/example/palayo/domain/auth/dto/request/LoginUserRequest.java
  src/main/java/com/example/palayo/domain/auth/dto/request/SignupUserRequest.java
  src/main/java/com/example/palayo/domain/auth/dto/response/LoginUserResponse.java
  src/main/java/com/example/palayo/domain/auth/dto/response/SignupUserResponse.java
  src/main/java/com/example/palayo/domain/auth/service/AuthService.java
  src/main/java/com/example/palayo/domain/user/controller/UserController.java
  src/main/java/com/example/palayo/domain/user/service/UserService.java
  src/test/java/com/example/palayo/auth/service/AuthServiceTest.java
  src/test/java/com/example/palayo/user/service/UserServiceTest.java
Labels: docs

#28 Feat/item image
  build.gradle
  src/main/java/com/example/palayo/common/controller/FileUploadController.java
  src/main/java/com/example/palayo/common/dto/ImageDeleteRequest.java
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/common/utils/FileSizeValidator.java
  src/main/java/com/example/palayo/common/utils/ImageExtensionValidator.java
  src/main/java/com/example/palayo/common/utils/S3Uploader.java
  src/main/java/com/example/palayo/config/S3Config.java
  src/main/java/com/example/palayo/domain/item/entity/Item.java
  src/main/java/com/example/palayo/domain/itemimage/controller/.gitkeep
  src/main/java/com/example/palayo/domain/itemimage/controller/ItemImageController.java
  src/main/java/com/example/palayo/domain/itemimage/dto/.gitkeep
  src/main/java/com/example/palayo/domain/itemimage/dto/request/CreateItemImageRequest.java
  src/main/java/com/example/palayo/domain/itemimage/dto/request/UpdateImageUrlRequest.java
  src/main/java/com/example/palayo/domain/itemimage/dto/request/UpdateItemImageRequest.java
  src/main/java/com/example/palayo/domain/itemimage/dto/response/ItemImageResponse.java
  src/main/java/com/example/palayo/domain/itemimage/entity/ItemImage.java
  src/main/java/com/example/palayo/domain/itemimage/repository/ItemImageRepository.java
  src/main/java/com/example/palayo/domain/itemimage/service/.gitkeep
  src/main/java/com/example/palayo/domain/itemimage/service/ItemImageService.java
Labels: feat

#30 test: PaymentServiceTest 작성
  src/main/java/com/example/palayo/domain/payment/TossPaymentClient.java
  src/main/java/com/example/palayo/domain/payment/dto/response/PaymentConfirmResponse.java
  src/test/java/com/example/palayo/dib/service/DibServiceTest.java
  src/test/java/com/example/palayo/payment/service/PaymentServiceTest.java
Labels: test

#31 feat: 알림 기능 구현
  .gitignore
  build.gradle
  firebase-messaging-sw.js
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/common/util/DataMapConverter.java
  src/main/java/com/example/palayo/common/util/JsonConverter.java
  src/main/java/com/example/palayo/config/CorsConfig.java
  src/main/java/com/example/palayo/config/FirebaseConfig.java
  src/main/java/com/example/palayo/config/RedisConfig.java
  src/main/java/com/example/palayo/config/SecurityConfig.java
  src/main/java/com/example/palayo/domain/auction/dto/request/CreateAuctionRequest.java
  src/main/java/com/example/palayo/domain/auction/scheduler/AuctionScheduler.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionServiceHelper.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionTimeUtils.java
  src/main/java/com/example/palayo/domain/auctionhistory/repository/AuctionHistoryRepository.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryServiceHelper.java
  src/main/java/com/example/palayo/domain/auth/dto/request/SignupUserRequest.java
  src/main/java/com/example/palayo/domain/dib/dto/response/DibResponse.java
  src/main/java/com/example/palayo/domain/dib/repository/DibRepository.java
  src/main/java/com/example/palayo/domain/dib/service/DibService.java
  src/main/java/com/example/palayo/domain/notification/controller/.gitkeep
  src/main/java/com/example/palayo/domain/notification/controller/NotificationController.java
  src/main/java/com/example/palayo/domain/notification/dto/.gitkeep
  src/main/java/com/example/palayo/domain/notification/dto/request/FcmTokenRequest.java
  src/main/java/com/example/palayo/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/example/palayo/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/palayo/domain/notification/dto/response/TokenResponse.java
  src/main/java/com/example/palayo/domain/notification/entity/.gitkeep
  src/main/java/com/example/palayo/domain/notification/entity/Notification.java
  src/main/java/com/example/palayo/domain/notification/entity/NotificationHistory.java
  src/main/java/com/example/palayo/domain/notification/enums/NotificationType.java
  src/main/java/com/example/palayo/domain/notification/factory/RedisNotificationFactory.java
  src/main/java/com/example/palayo/domain/notification/redis/RedisNotification.java
  src/main/java/com/example/palayo/domain/notification/repository/.gitkeep
  src/main/java/com/example/palayo/domain/notification/repository/NotificationHistoryRepository.java
  src/main/java/com/example/palayo/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/palayo/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/example/palayo/domain/notification/scheduler/RedisNotificationScheduler.java
  src/main/java/com/example/palayo/domain/notification/service/.gitkeep
  src/main/java/com/example/palayo/domain/notification/service/NotificationService.java
  src/main/java/com/example/palayo/domain/user/repository/UserRepository.java
  src/main/resources/prod/application-datasource.yml
  src/main/resources/template/testpage.html
  src/test/java/com/example/palayo/domain/notification/NotificationServiceTest.java
Labels: feat

#34 feat: Auction에 낙찰 및 입찰 보증금/포인트 처리 로직 추가
  .gitignore
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/domain/auction/scheduler/AuctionScheduler.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionServiceHelper.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionTimeUtils.java
  src/main/java/com/example/palayo/domain/auctionhistory/repository/AuctionHistoryRepository.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryServiceHelper.java
  src/main/java/com/example/palayo/domain/deposithistory/controller/DepositHistoryController.java
  src/main/java/com/example/palayo/domain/deposithistory/entity/DepositHistory.java
  src/main/java/com/example/palayo/domain/deposithistory/enums/DepositStatus.java
  src/main/java/com/example/palayo/domain/deposithistory/repository/DepositHistoryRepository.java
  src/main/java/com/example/palayo/domain/deposithistory/service/DepositHistoryService.java
  src/main/java/com/example/palayo/domain/dib/service/DibService.java
  src/main/java/com/example/palayo/domain/payment/service/PaymentService.java
  src/main/java/com/example/palayo/domain/pointhistory/repository/PointHistoriesRepository.java
  src/main/java/com/example/palayo/domain/pointhistory/service/PointHistoriesService.java
  src/main/java/com/example/palayo/domain/user/enums/PointType.java
  src/test/java/com/example/palayo/auction/service/AuctionServiceTest.java
  src/test/java/com/example/palayo/auctionhistory/service/AuctionHistoryServiceTest.java
Labels: feat

#33 refactor: 아이템, 아이템이미지 리팩토링
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/domain/auction/repository/AuctionRepository.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionValidator.java
  src/main/java/com/example/palayo/domain/deposithistory/controller/DepositHistoryController.java
  src/main/java/com/example/palayo/domain/deposithistory/service/DepositHistoryService.java
  src/main/java/com/example/palayo/domain/item/controller/ItemController.java
  src/main/java/com/example/palayo/domain/item/entity/Item.java
  src/main/java/com/example/palayo/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/example/palayo/domain/item/repository/ItemRepositoryImpl.java
  src/main/java/com/example/palayo/domain/item/service/ItemService.java
  src/main/java/com/example/palayo/domain/item/util/ItemValidator.java
  src/main/java/com/example/palayo/domain/itemimage/controller/ItemImageController.java
  src/main/java/com/example/palayo/domain/itemimage/dto/request/CreateItemImageRequest.java
  src/main/java/com/example/palayo/domain/itemimage/dto/request/UpdateImageUrlRequest.java
  src/main/java/com/example/palayo/domain/itemimage/dto/request/UpdateItemImageRequest.java
  src/main/java/com/example/palayo/domain/itemimage/dto/response/ItemImageResponse.java
  src/main/java/com/example/palayo/domain/itemimage/entity/ItemImage.java
  src/main/java/com/example/palayo/domain/itemimage/repository/ItemImageRepository.java
  src/main/java/com/example/palayo/domain/itemimage/service/ItemImageService.java
Labels: refactor

#45 Feat/payment pr 재시도
  .gitignore
  .run/console.sql.run.xml
  Docker-Compose.yml
  build.gradle
  src/main/java/com/example/palayo/PalayoApplication.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryServiceHelper.java
  src/main/java/com/example/palayo/domain/payment/service/PaymentService.java
  src/main/java/com/example/palayo/domain/pointhistory/mongo/controller/PointHistoryController.java
  src/main/java/com/example/palayo/domain/pointhistory/mongo/document/PointHistoryDocument.java
  src/main/java/com/example/palayo/domain/pointhistory/mongo/dto/PointHistoryResponse.java
  src/main/java/com/example/palayo/domain/pointhistory/mongo/repository/PointHistoryRepository.java
  src/main/java/com/example/palayo/domain/pointhistory/mongo/service/PointHistoryService.java
  src/test/java/com/example/palayo/payment/service/PaymentServiceTest.java
Labels: feat

#46 fix : 몽고 디비 추가로 인한 중복 포인트 증가 수정, 닉네임 변경 로직의 오류를 발견하여 수정
  src/main/java/com/example/palayo/domain/pointhistory/mongo/service/PointHistoryService.java
  src/main/java/com/example/palayo/domain/user/service/UserService.java
  src/test/java/com/example/palayo/user/service/UserServiceTest.java
Labels: fix

#48 feat: 경매 입찰 및 낙찰 관련 기능 개선
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/domain/auction/dto/request/CreateAuctionRequest.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionResponse.java
  src/main/java/com/example/palayo/domain/auction/entity/Auction.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionServiceHelper.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionValidator.java
  src/main/java/com/example/palayo/domain/auctionhistory/repository/AuctionHistoryRepository.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryServiceHelper.java
  src/main/java/com/example/palayo/domain/deposithistory/repository/DepositHistoryRepository.java
  src/main/java/com/example/palayo/domain/user/repository/UserRepository.java
  src/test/java/com/example/palayo/PalayoApplicationTests.java
  src/test/java/com/example/palayo/auction/service/AuctionServiceTest.java
Labels: feat

#52 fix: 경매 낙찰 처리 시 상태 전환 및 보증금 예외 처리 개선
  src/main/java/com/example/palayo/domain/auction/entity/Auction.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionServiceHelper.java
  src/main/java/com/example/palayo/domain/deposithistory/service/DepositHistoryService.java
Labels: fix

#74 feat: 경매 낙찰/포인트/동시성 로직 개선 및 책임 분리
  build.gradle
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/domain/auction/dto/request/CreateAuctionRequest.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionDetailResponse.java
  src/main/java/com/example/palayo/domain/auction/dto/response/AuctionListResponse.java
  src/main/java/com/example/palayo/domain/auction/entity/Auction.java
  src/main/java/com/example/palayo/domain/auction/scheduler/AuctionScheduler.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionServiceHelper.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionTimeUtils.java
  src/main/java/com/example/palayo/domain/auction/util/AuctionValidator.java
  src/main/java/com/example/palayo/domain/auction/util/TimeFormatter.java
  src/main/java/com/example/palayo/domain/auctionhistory/repository/AuctionHistoryRepository.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryServiceHelper.java
  src/main/java/com/example/palayo/domain/auth/service/AuthService.java
  src/main/java/com/example/palayo/domain/pointhistory/mongo/service/PointHistoryService.java
  src/main/java/com/example/palayo/domain/pointhistory/service/PointHistoriesService.java
  src/main/java/com/example/palayo/domain/user/entity/User.java
  src/main/java/com/example/palayo/domain/user/enums/PointType.java
Labels: feat

#75 feat : websocket 입찰에 대하여 웹소켓 기능 개발
  .gitignore
  build.gradle
  gradlew
  src/main/java/com/example/palayo/PalayoApplication.java
  src/main/java/com/example/palayo/common/dto/AuthUser.java
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/config/AuthUserHandshakeHandler.java
  src/main/java/com/example/palayo/config/CorsConfig.java
  src/main/java/com/example/palayo/config/JwtAuthenticationFilter.java
  src/main/java/com/example/palayo/config/JwtHandshakeInterceptor.java
  src/main/java/com/example/palayo/config/JwtUtil.java
  src/main/java/com/example/palayo/config/SecurityConfig.java
  src/main/java/com/example/palayo/config/WebsocketConfig.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/request/CreateBidRequest.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/response/BidHistoryResponse.java
  src/main/java/com/example/palayo/domain/auctionhistory/dto/response/BidResponse.java
  src/main/java/com/example/palayo/domain/auctionhistory/service/AuctionHistoryService.java
  src/main/java/com/example/palayo/domain/auth/service/AuthService.java
  src/main/java/com/example/palayo/domain/websocket/controller/BidWebSocketController.java
  src/main/resources/application.yml
  src/main/resources/static/BidWebSocket.html
  src/test/java/com/example/palayo/auth/service/AuthServiceTest.java
  src/test/java/com/example/palayo/depositHistory/DepositHistoryServiceTests.java
  src/test/java/com/example/palayo/dib/service/DibServiceTest.java
Labels: feat
