Repository palayo-auction/palayo-auction, pull requests merged in 2025-05, with the labels that each got.

#78 feat: 찜하기 기능에 Redis 캐시 도입
  Docker-Compose.yml
  src/main/java/com/example/palayo/config/RedisConfig.java
  src/main/java/com/example/palayo/domain/dib/controller/DibController.java
  src/main/java/com/example/palayo/domain/dib/dto/response/DibRedisCacheResponse.java
  src/main/java/com/example/palayo/domain/dib/service/DibService.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/example/palayo/PalayoApplicationTests.java
Labels: feat

#80 fix: 찜하기 Service 코드 수정
  src/test/java/com/example/palayo/dib/service/DibServiceTest.java
Labels: fix

#84 Feat/deposithistory
  src/main/java/com/example/palayo/common/exception/ErrorCode.java
  src/main/java/com/example/palayo/config/QuartzConfig.java
  src/main/java/com/example/palayo/domain/auction/job/AuctionEndJob.java
  src/main/java/com/example/palayo/domain/auction/job/AuctionStartJob.java
  src/main/java/com/example/palayo/domain/auction/scheduler/AuctionScheduler.java
  src/main/java/com/example/palayo/domain/auction/service/AuctionService.java
  src/main/resources/logback-spring.xml
Labels: style
